version: '3'
services:
  mongo:
    image: mongo
    restart: always
  jguweka:
    image: sharpmaple/restweka
    restart: always
    links:
      - "mongo:mongodb"
    #ports:
     # - "8080:8080"
    depends_on:
      - mongo
    labels:
      - "service-name:jguweka"
      - "service-type:app-srv"
      - "environment:test"
